#!/usr/bin/env bash
# =============================================================================
# scripts/haproxy/02-configure-haproxy.sh
#
# Write the HAProxy configuration and start the service.
# Run ONLY on the HAProxy instance, after 01-install-haproxy.sh.
#
# Usage:
#   sudo bash 02-configure-haproxy.sh <master1-ip> [master2-ip] [master3-ip]
#
#   # Or pipe all IPs space-separated:
#   sudo bash 02-configure-haproxy.sh 10.0.10.10 10.0.10.11 10.0.10.12
#
# What this script does:
#   1. Accept master IPs as positional arguments
#   2. Write /etc/haproxy/haproxy.cfg
#   3. Validate config with haproxy -c
#   4. Restart HAProxy
#   5. Verify port 6443 is listening
#   6. Check stats page on port 8404
#
# Idempotent — safe to re-run with same or updated master IPs.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../common/config.env"
source "${SCRIPT_DIR}/../common/lib/logging.sh"
source "${SCRIPT_DIR}/../common/lib/utils.sh"

trap 'log_trap_error ${LINENO}' ERR

log_section "HAProxy Configuration"

require_root

# ---------------------------------------------------------------------------
# Arguments — master IPs
# ---------------------------------------------------------------------------
if [[ $# -lt 1 ]]; then
  log_error "Usage: $0 <master1-ip> [master2-ip] [master3-ip]"
  exit 1
fi

MASTER_IPS=("$@")
log_info "Configuring HAProxy for ${#MASTER_IPS[@]} master(s): ${MASTER_IPS[*]}"

# ---------------------------------------------------------------------------
# Build backend server lines
# ---------------------------------------------------------------------------
BACKEND_LINES=""
for i in "${!MASTER_IPS[@]}"; do
  IDX=$((i + 1))
  IP="${MASTER_IPS[$i]}"
  BACKEND_LINES+="    server master-${IDX} ${IP}:${API_SERVER_PORT} check fall 3 rise 2\n"
done

# ---------------------------------------------------------------------------
# Write /etc/haproxy/haproxy.cfg
# ---------------------------------------------------------------------------
log_section "Step 1/4 — Write HAProxy config"

# Backup existing config if present
if [[ -f /etc/haproxy/haproxy.cfg ]]; then
  cp /etc/haproxy/haproxy.cfg "/etc/haproxy/haproxy.cfg.bak.$(date +%Y%m%d%H%M%S)"
  log_info "Backed up existing config"
fi

cat > /etc/haproxy/haproxy.cfg <<EOF
#----------------------------------------------------------------------
# HAProxy Configuration — Kubernetes API Server Load Balancer
# Generated by: scripts/haproxy/02-configure-haproxy.sh
# Masters: ${MASTER_IPS[*]}
#----------------------------------------------------------------------

global
    log         /dev/log local0
    log         /dev/log local1 notice
    maxconn     4096
    daemon

defaults
    log         global
    mode        tcp
    option      tcplog
    option      dontlognull
    timeout connect 5s
    timeout client  50s
    timeout server  50s

#----------------------------------------------------------------------
# Frontend — accepts Kubernetes API connections on port 6443
#----------------------------------------------------------------------
frontend k8s-api
    bind *:${API_SERVER_PORT}
    mode tcp
    option tcplog
    default_backend k8s-masters

#----------------------------------------------------------------------
# Backend — round-robin to all control plane nodes
# fall 3 : mark DOWN after 3 consecutive failed TCP health checks
# rise 2 : mark UP  after 2 consecutive successful health checks
#----------------------------------------------------------------------
backend k8s-masters
    mode tcp
    balance roundrobin
    option tcp-check
$(echo -e "${BACKEND_LINES}")
#----------------------------------------------------------------------
# Stats page — http://<haproxy-ip>:8404/stats
#----------------------------------------------------------------------
frontend stats
    bind *:8404
    mode http
    stats enable
    stats uri /stats
    stats refresh 10s
    stats show-legends
    stats show-node
    no log
EOF

log_info "HAProxy config written to /etc/haproxy/haproxy.cfg"

# ---------------------------------------------------------------------------
# Validate config
# ---------------------------------------------------------------------------
log_section "Step 2/4 — Validate HAProxy config"

if haproxy -c -f /etc/haproxy/haproxy.cfg; then
  log_info "HAProxy config validation PASSED ✓"
else
  log_error "HAProxy config validation FAILED"
  log_error "Check /etc/haproxy/haproxy.cfg for syntax errors"
  exit 1
fi

# ---------------------------------------------------------------------------
# Restart HAProxy
# ---------------------------------------------------------------------------
log_section "Step 3/4 — Restart HAProxy"

service_restart haproxy
log_info "HAProxy restarted"

# ---------------------------------------------------------------------------
# Verify port 6443 is listening
# ---------------------------------------------------------------------------
log_section "Step 4/4 — Verify HAProxy is listening"

sleep 2

if ss -tlnp 2>/dev/null | grep -q ":${API_SERVER_PORT}"; then
  log_info "HAProxy is listening on port ${API_SERVER_PORT} ✓"
elif netstat -tlnp 2>/dev/null | grep -q ":${API_SERVER_PORT}"; then
  log_info "HAProxy is listening on port ${API_SERVER_PORT} ✓"
else
  log_error "HAProxy is NOT listening on port ${API_SERVER_PORT}"
  systemctl status haproxy --no-pager || true
  exit 1
fi

if ss -tlnp 2>/dev/null | grep -q ":8404"; then
  log_info "HAProxy stats page listening on port 8404 ✓"
fi

log_section "HAProxy Configuration COMPLETE ✓"
log_info "API endpoint: $(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || hostname -I | awk '{print $1}'):${API_SERVER_PORT}"
log_info "Stats page  : http://$(hostname -I | awk '{print $1}'):8404/stats"
