#------------------------------------------------------------------------------
# HAProxy Configuration — Kubernetes API Server Load Balancer
# Generated by Terraform. Do not edit manually.
# Template variables are injected by the haproxy Terraform module.
#------------------------------------------------------------------------------

global
  log         /dev/log local0
  log         /dev/log local1 notice
  maxconn     ${maxconn}
  daemon

defaults
  log         global
  mode        tcp
  option      tcplog
  option      dontlognull
  timeout connect ${timeout_connect}
  timeout client  ${timeout_client}
  timeout server  ${timeout_server}
  errorfile 400 /etc/haproxy/errors/400.http
  errorfile 403 /etc/haproxy/errors/403.http
  errorfile 408 /etc/haproxy/errors/408.http
  errorfile 500 /etc/haproxy/errors/500.http
  errorfile 502 /etc/haproxy/errors/502.http
  errorfile 503 /etc/haproxy/errors/503.http
  errorfile 504 /etc/haproxy/errors/504.http

#------------------------------------------------------------------------------
# Frontend — listens for Kubernetes API server connections on port 6443
#------------------------------------------------------------------------------
frontend k8s-api
  bind *:${frontend_port}
  mode tcp
  option tcplog
  default_backend k8s-masters

#------------------------------------------------------------------------------
# Backend — round-robin distribution to all control plane nodes
# fall 3  : mark server DOWN after 3 consecutive failed health checks
# rise 2  : mark server UP after 2 consecutive successful health checks
#------------------------------------------------------------------------------
backend k8s-masters
  mode tcp
  balance roundrobin
  option tcp-check
${backend_servers}

#------------------------------------------------------------------------------
# Stats page — useful for monitoring HAProxy health
# Access: http://<haproxy-ip>:${stats_port}${stats_uri}
#------------------------------------------------------------------------------
frontend stats
  bind *:${stats_port}
  mode http
  stats enable
  stats uri ${stats_uri}
  stats refresh 10s
  stats show-legends
  stats show-node
  no log
